version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3320:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    driver: bridge
